
# 1. Запрещаем вход по паролю (самое важное от брутфорса)
# по паролю нельзя, только по ключу
PasswordAuthentication no
# никаких дополнительных форм аутентификации нельзя (например, по одноразовым паролям)
ChallengeResponseAuthentication no
# использование системных механизмов аутентификации (лимиты сессий, логирование в журнал и т.п.)
UsePAM yes
# отключаем интерактивную аутентификацию с клавиатуры
KbdInteractiveAuthentication no

# 2. Разрешаем вход только по ключам
PubkeyAuthentication yes
# указываем, где лежат ключи
AuthorizedKeysFile .ssh/authorized_keys

# 3. Ограничиваем вход для root (только по ключу, или вообще запрещаем)
# Если хочешь совсем закрыть рута: PermitRootLogin no
# Если только по ключу: PermitRootLogin prohibit-password
PermitRootLogin no

# 4. Явно разрешаем вход только твоему юзеру
AllowUsers nornad

# 5. Отключаем пустые пароли и лишние функции
# пустые пароли нельзя
PermitEmptyPasswords no
# окна не пробрасываем
X11Forwarding no
# максимум попыток логина
MaxAuthTries 2
# время на 1 попытку ввода пароля или ключа
LoginGraceTime 10
# разрешаем туннелирование для доступа к панели 3X-UI. но обычно туннелирование не требуется
AllowTcpForwarding yes
# проверка живая ли ещё сессия
TCPKeepAlive yes
# раз в 60 секунд шлём пустой пакет клиенту для проверки, жив ли он ещё
ClientAliveInterval 60
# если 3 раза не получили ответ на пустой пакет - разрываем соединение
ClientAliveCountMax 3
# ограничение количества одновременных неавторизованных подключений (на этапе ввода пароля или обмена ключами)
# до 10 одновременных попыток входа - пускаем всех
# если одновременных попыток больше 10 - сбрасываем 30% новых. чем больше попыток, тем больше процент сброса
# если одновременно стучаться 60 и более ботов - сбрасываем ВСЕХ, пока кто-то из тех 60 не залогинится или не отвалится
MaxStartups 10:30:60
# печать при подключении информации о том, когда был последний логин
PrintLastLog yes
# позволяем клиенту передавать настройки языка и кодировки, чтобы кириллица и спецсимволы отображались нормально
AcceptEnv LANG LC_*
# включаем поддержку SFTP, чтобы можно было удобнее файлы заливать на сервер по ssh. или стягивать с него
Subsystem sftp /usr/lib/openssh/sftp-server
# разрешаем вход только тем пользователям, которые состоят в указанной группе. если указать и пользователей, и группу, для подключения надо будет быть и там и там
# # sudo groupadd sshauth
# # sudo usermod -aG sshauth твое_имя_юзера
# AllowGroups sshauth
